# Generated by Django 5.1.6 on 2025-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='Hello', max_length=300),
            preserve_default=False,
        ),
    ]
